### ISSUE TITLE
FunctionTransformer has an unsupported value (Python class numpy.core._multiarray_umath.log)

### ISSUE THREAD

**Issue by aedenj** [jpmml/jpmml-python#10]
I'm attempting to build a simple LinearRegression pipeline that performs some preprocessing. The code is roughly,

```
X = data.filter(items=['Width'])
y = data['Weight']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


mapper = DataFrameMapper([
    (["Width"], [ContinuousDomain(), FunctionTransformer(np.log)])
])

model_pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("model", LinearRegression())
])

clf = model_pipeline.fit(X_train, y_train);
sklearn2pmml(clf, 'model.pmml', with_repr=True, debug=True)
```

However I get the following error,

```
python: 3.8.8
sklearn: 0.24.1
sklearn2pmml: 0.69.0
joblib: 1.0.1
sklearn_pandas: 2.1.0
pandas: 1.2.3
numpy: 1.20.2
openjdk: 1.8.0_282
Executing command:
java -cp /opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/gson-2.8.6.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/guava-21.0.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-genmodel-3.32.0.4.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-logger-3.32.0.4.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-tree-api-0.3.17.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/istack-commons-runtime-3.0.11.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jakarta.activation-1.2.2.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jakarta.xml.bind-api-2.3.3.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jaxb-runtime-2.3.3.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jcommander-1.72.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-converter-1.4.6.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-h2o-1.1.4.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.3.6.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-python-1.0.11.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.6.15.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.5.0.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/pickle-1.1.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-model-1.5.11.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-model-metro-1.5.11.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/serpent-1.30.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/slf4j-api-1.7.30.jar:/opt/conda/lib/python3.8/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.30.jar org.jpmml.sklearn.Main --pkl-pipeline-input /tmp/pipeline-q4tmq2kn.pkl.z --pmml-output fish-weight-model.pmml
Standard output is empty
Standard error:
Apr 05, 2021 5:09:27 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Apr 05, 2021 5:09:27 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 19 ms.
Apr 05, 2021 5:09:27 AM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Apr 05, 2021 5:09:27 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: Attribute 'sklearn.preprocessing._function_transformer.FunctionTransformer.func' has an unsupported value (Python class numpy.core._multiarray_umath.log)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at org.jpmml.python.PythonObject.get(PythonObject.java:91)
	at org.jpmml.python.PythonObject.getOptional(PythonObject.java:101)
	at sklearn.preprocessing.FunctionTransformer.getFunc(FunctionTransformer.java:68)
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:44)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDictConstructor to org.jpmml.python.Identifiable
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 12 more

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn.preprocessing._function_transformer.FunctionTransformer.func' has an unsupported value (Python class numpy.core._multiarray_umath.log)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at org.jpmml.python.PythonObject.get(PythonObject.java:91)
	at org.jpmml.python.PythonObject.getOptional(PythonObject.java:101)
	at sklearn.preprocessing.FunctionTransformer.getFunc(FunctionTransformer.java:68)
	at sklearn.preprocessing.FunctionTransformer.encodeFeatures(FunctionTransformer.java:44)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDictConstructor to org.jpmml.python.Identifiable
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 12 more
```

Any help would be appreciated.

**Comment by vruusmann** [comment]
Support for Numpy functions was heavily refactored/updated in 88b15f01f7c92f66c.

There are tests for pickling/unpickling all supported Numpy ufuncs:
https://github.com/jpmml/jpmml-python/blob/1.0.12/src/test/resources/ufunc.py

Relevant Python-to-Java class mappings:
https://github.com/jpmml/jpmml-python/blob/1.0.12/src/main/resources/META-INF/python2pmml.properties#L5-L7

I tested everything with Numpy 1.20.0. Worked just fine - the `log` function was stored as `numpy.log` object. How the hell is it mapped to `numpy.core._multiarray_umath.log` in Numpy 1.20.2 now?

**Comment by vruusmann** [comment]
Try importing your ufuncs like here:
https://github.com/jpmml/jpmml-python/blob/1.0.12/src/test/resources/ufunc.py#L11

Does this issue only affect the `log` function, or are all functions unavailable?

**Comment by vruusmann** [comment]
Alternatively, use `sklearn2pmml.preprocessing.ExpressionTransformer`:

```python
from sklearn2pmml.preprocessing import ExpressionTransformer

mapper = DataFrameMapper([
    (["Width"], [ContinuousDomain(), ExpressionTransformer("numpy.log(X[0])")])
])
```

**Comment by aedenj** [comment]
Thanks for responding @vruusmann. 

It appears this same message occurs for a number of the functions under 1.20.2. I tried,

np.abs -- ... has an unsupported value (Python class numpy.core._multiarray_umath.absolute)
np.exp -- ... has an unsupported value (Python class numpy.core._multiarray_umath.exp)
np.log1p -- ... has an unsupported value (Python class numpy.core._multiarray_umath.exp)

I did install numpy 1.20.0 using `pip install numpy==1.20.0` and I received the same message. 

Just in case this context matters I'm running the sample code above in an instance of Jupyter Notebooks using this [Jupyter Stacks docker image.](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook) I went through the docker image file(s), but I'm relatively new to the python echo system. The one thing that does stand out is the fact that the base image, https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile, uses conda instead of pip to install packages. Perhaps this can lead to pathing differences. 


Re: (["Width"], [ContinuousDomain(), ExpressionTransformer("numpy.log(X[0])")])

I did end up doing that. I was hoping to get to the root cause of this because I get the same error for the model
step I'd like to have.

```
("model", TransformedTargetRegressor(regressor=LinearRegression(), func=np.log, inverse_func=np.exp))
```

**Comment by vruusmann** [comment]
> It appears this same message occurs for a number of the functions under 1.20.2.

Can you run my `ufunc.py` script in a new directory, and share the contents of the resulting `ufunc/` directory to me (create a ZIP archive, and then attach it to this issue, or send it to my e-mail)?
https://github.com/jpmml/jpmml-python/blob/1.0.12/src/test/resources/ufunc.py

This script would cover all supported functions. Perhaps there are some module location irregularities somewhere.

For example, in my computer, only the `numpy.ceil` function was "misplaced". I wonder if in your computer/encvironment all Numpy ufuncs reside in the `numpy.core._multiarray_umath` module or not.

**Comment by aedenj** [comment]
I attempted to run the script `ufunc.py`, but received the following error.

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from common import _pickle, _platform_module
ModuleNotFoundError: No module named 'common'
```

I ran `pip install common`, but received the error 

```
ImportError: cannot import name '_pickle' from 'common' (/opt/conda/lib/python3.8/site-packages/common/__init__.py)
```

**Comment by aedenj** [comment]
Here's the output I believe you asked for.

[ufuncs.tar.gz](https://github.com/jpmml/jpmml-python/files/6262399/ufuncs.tar.gz)

**Comment by vruusmann** [comment]
Thanks - I've dumped those pickle files into test resources directory, and added missing Python-to-Java class mappings.

The fix should make into the SkLearn2PMML package in about a week.

**Comment by aedenj** [comment]
Thank you so much for your lightning quick follow up.

**Comment by vruusmann** [comment]
> Thank you so much for your lightning quick follow up.

The SkLearn2PMML package update is still pending - will happen by Monday.

Today, you can check out the `HEAD` version of the JPMML-SkLearn library (includes JPMML-Python version 1.0.13), and perform PMML conversion using its command-line application interface.
