### ISSUE TITLE
Nested ifelse is not working in Expression Transformer

### ISSUE THREAD

**Issue by sachinsinha620** [jpmml/jpmml-python#11]
I am using nested ifelse in expression transformer. While generating PMML I am getting below error,

'Python Expression is either invalid or not supported'

Kindly suggest how can we use nested ifelse in expression transformer.

**Comment by vruusmann** [comment]
Looks like my Python language grammar (for generating the parser) needs updating.

This works (plain if-else):
```python
ExpressionTransformer("1 if X[0] > 30 else 0")
```

This doesn't work (nested if-else):
```python
ExpressionTransformer("1 if X[0] > 30 else 0.5 if X[0] > 20 else 0")
```

The workaround for now is to "escape" child if-else statements using parentheses:
```python
ExpressionTransformer("1 if X[0] > 30 else (0.5 if X[0] > 20 else 0)")
```

**Comment by sachinsinha620** [comment]
Thanks for your reply.

In my code I was using below expression first and then nested if else. Below was working fine till yesterday but now it also started giving same error i.e "java.lang.IllegalArgumentException: Python expression ''-999.01' if (X[0][0:4]=='1900') else X[0][11:13]' is either invalid or not supported"

"'-999.01' if (X[0][0:4]=='1900') else X[0][11:13]"

**Comment by sachinsinha620** [comment]
And this one requires paranthesis on the else parts:


" '18-34' if X[0] >= 18 else '13-18' if X[0] >= 13 else '7-12' if X[0] >= 7 else '0-6' if X[0] >= 0 else '' "
