### ISSUE TITLE
how *.pkl file to pmml

### ISSUE THREAD

**Issue by farsunset** [jpmml/jpmml-python#12]
how *.pkl file to pmml

**Comment by vruusmann** [comment]
The JPMML-Python library is a general-purpose library for Java application developers. It does not provide any command-line tools, although this may change in the future (eg. see #4 ).

If you know what's inside the PKL file, then you may try using more specialized [JPMML](https://github.com/jpmml) command-line applications.

For example, if the PKL file contains Scikit-Liearn object(s), then use the `org.jpmml.sklearn.Main` command-line application from the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) project:
https://github.com/jpmml/jpmml-sklearn#usage
