### ISSUE TITLE
Scipy in ExpressionTransformer

### ISSUE THREAD

**Issue by ban2903** [jpmml/jpmml-python#16]
Hello Villu,
How can I use a scipy tools in ExpressionTransformer? Or where can I read about libraries which are support ExpressionTransformer
```python
('feature', ExpressionTransformer('scipy.special.logit(X[0])'))
```
PMML said "No module name scipy". Version 0.74.1

(I know, that I can use `numpy.log(X[0]/(1-X[0]))`, but maybe scipy will work for me?)

**Comment by vruusmann** [comment]
> where can I read about libraries which are support ExpressionTransformer

The Python expression parser component is provided by the JPMML-Python module (hence transferred this issue over to there).

Formal grammar:
https://github.com/jpmml/jpmml-python/blob/1.1.2/pmml-python/src/main/javacc/expression.jj

Supported Python functions (both built-in and 3rd party ones) have been hand-coded one by one like this:
https://github.com/jpmml/jpmml-python/blob/1.1.2/pmml-python/src/main/javacc/expression.jj#L213-L231

Then jump into the `numpy.core.FunctionUtil` utility class to see what's currently available:
https://github.com/jpmml/jpmml-python/blob/1.1.2/pmml-python/src/main/java/numpy/core/FunctionUtil.java

> I know, that I can use numpy.log(X[0]/(1-X[0])), but maybe scipy will work for me?

If I were to implement `scipy.special.logit` function into the JPMML library stack, then I'd pretty much be hard-coding the similar business logic.

The point is that there is no way to automate Python-to-PMML function translation. It has to be typed in manually as feature requests come in.

**Comment by vruusmann** [comment]
This feature request got me thinking that it would be nice to have a mechanism so that users could define "soft" function aliases.

In the current case, the user could centrally define a mapping/pattern `scipy.special.logit(X[$index])` => `numpy.log(X[$index]/(1-X[$index]))`, which would then be automatically replaced during conversion.

**Comment by vruusmann** [comment]
@ban2903 Do you need any other Scipy functions? If I were to work on this issue, then I'd like to implement more than function (to justify the effort).

**Comment by ban2903** [comment]
Mapping/pattern idea is very cool

I also use scipy.special.expit and numpy.where(X[0]==1, 1, 0). But numpy.where also does not work.

By the way, the reason why I would like to see logit and similar functions:
`X[0] if (X[0] is None) else (numpy.log(X[0]/(1-X[0])) if numpy.log(X[0]/(1-X[0])) > -4 and numpy.log(X[0]/(1-X[0])) < 0 else (-4.0 if numpy.log(X[0]/(1-X[0])) <= -4 else 0.0))`
We could write: `numpy.clip(scipy.special.logit(X[0]), -4.0, 0.0)`

**Comment by vruusmann** [comment]
> Mapping/pattern idea is very cool

I'm thinking about a solution, where you could use a proper Python expression as the main part, and then provide extra "substitutions" for the Python-to-PMML conversion part.

Something like this:
```python
transformer = ExpressionTransformer(
  expr = "numpy.clip(scipy.special.logit(X[0]), -4.0, 0.0)", 
  expansions = {
    "scipy.special.logit(X[$index])" : "numpy.log(X[$index]/(1-X[$index]))"
  }
)
```

The dict of expansions could be defined as some global variable, and shared between team members.

> I also use scipy.special.expit

OK, now there are two SciPy functions that need attention!

> But numpy.where also does not work

The `numpy.where` function is a data table-oriented function (ie. operates on a list of rows). Most PMML translatable functions are data row-oriented (ie. operates on a single row).

Maybe it can be used in limited scenarious. But it would be a different issue then.

> We could write: numpy.clip(scipy.special.logit(X[0]), -4.0, 0.0)

The `numpy.clip` function should be supported by recent SkLearn2PMML package versions:
https://github.com/jpmml/jpmml-python/blob/1.1.2/pmml-python/src/main/java/numpy/core/FunctionUtil.java#L66-L73

**Comment by vruusmann** [comment]
> We could write: numpy.clip(scipy.special.logit(X[0]), -4.0, 0.0)

Another suggestion for structuring your Python code - use two consecutive `ExpressionTransformer` steps instead of a single one - the first step computes the `logit` function, and the second step then clips it:

```python
mapper = DataFrameMapper([
  (num_col, [ContinuousDomain(), ExpressionTransformer("logit(X[0]")), ExpressionTransformer("numpy.clip(X[0], -4.0, 0.0)")])
])
```

This way you don't need to type out the complex part multiple times, it stays in a single hot-spot.

**Comment by ban2903** [comment]
Im not sure if this will make things easuer because we still write a crutch in the form transformer  `"numpy.log(X[$index]/(1-X[$index]))"` :( 

Maybe you know analogues of `numpy.where`?  because this way `X[0] if (X[0] is None) else (1 if X[0] <= 1.2 else X[0])`  haunts a lot of syntax errors

**Comment by vruusmann** [comment]
> Maybe you know analogues of `numpy.where`?

You mean using `numpy.where` as an alternative form of Python's if-else statement? That is, in Python it would be evaluated as a normal Numpy UFunc, but the PMML converter would translate it to a PMML 'if' function.

If so, sounds very much doable!

**Comment by ban2903** [comment]
> но преобразователь PMML преобразует его в функцию PMML 'if'.

Yeah!
But It's up to you how confortable it is...
In my opinion, it is usefull
