### ISSUE TITLE
Feature request: power ufunc

### ISSUE THREAD

**Issue by bindernet** [jpmml/jpmml-python#5]
Hi Villu.
I notice in UFuncUtil.java that PMMLFunctions.POW already exists and is used for square.
Is it now possible to pass 2 params and implement this?

**Comment by bindernet** [comment]
I can see there's a `PowerFunctionTransformer`. What I'm ultimately looking to do is create a rounding transformer, something like
```
ExpressionTransformer(
        f"numpy.rint(X[0] * numpy.power(10.0, {places})) / numpy.power(10.0, {places})"
    )
```

**Comment by vruusmann** [comment]
Back in the day when the Python expression parser component was still part of the JPMML-SkLearn library, then it only supported unary (aka one-arg) functions.

The `numpy.power` function is a binary (aka two-arg) function. Hence it couldn't be supported.

The Python expression parser component has been refactored now.

@bindernet Are you interested in any other multi-ary numpy functions besides `numpy.power`? Now is the time to ask!

**Comment by bindernet** [comment]
Thanks! That's my urgent need right now. Looking at the list of universal functions with 2 parameters, ,float_power could also be useful in certain circumstances.
